### ISSUE TITLE
Support specifying CLI version

### ISSUE THREAD

**Issue by umcodemonkey** [Distelli/DistelliAgentCookbook#2]
The pre-rewrite recipe allowed an attribute to specify a specific version of the agent to be installed, which is critical to stable, repeatable deployments. Support for this should be restored to this recipe. See docs for reference.

https://www.distelli.com/docs/reference/distelli-agent#install-a-specific-agent-version

**Comment by brimworks** [comment]
Good call, we should be able to do this.

**Comment by brimworks** [comment]
This should do it:

https://github.com/Distelli/DistelliAgentCookbook/commit/602a2f5b4f836571c0ce5aa0509eeefff79efc70

...although I haven't tested it since we don't use chef.

**Comment by brimworks** [comment]
Tested and implemented.
