### ISSUE TITLE
Support specifying predefined environments

### ISSUE THREAD

**Issue by umcodemonkey** [Distelli/DistelliAgentCookbook#3]
The `distelli.yml` file allows the machine to specify which environments the server should join when the agent is installed. This should be supported by this recipe and its template.

https://www.distelli.com/docs/reference/distelli-distelliyml-usage#specifying-environment

**Comment by brimworks** [comment]
Yep, we should do this too :+1:

**Comment by brimworks** [comment]
In our meeting earlier today I think you eluded to the fact that prior versions of the cookbook supported this, but I don't see anything in here to indicate that it was previously supported:

https://github.com/Distelli/DistelliAgentCookbook/blob/2592298c2cb4a9bb5a487aa8d812d188615564cd/templates/default/distelli.yml.erb

Did you have a fork that supported this? If so, what was the names of the attributes (so I can be sure my implementation is compatible).

Thanks,
-Brian

**Comment by umcodemonkey** [comment]
Sorry, no, we built our own recipe that used this one and added that template support. Feel free implement however makes sense to you; our template looked like:

```
<% if node[:distelli][:agent][:environments].size > 0 %>
Environments:
<% node[:distelli][:agent][:environments].each do |env| %>
  - <%= env %>
<% end %>
<% end %>
```

**Comment by brimworks** [comment]
Again, I haven't tested this, but this should hypothetically work now:

https://github.com/Distelli/DistelliAgentCookbook/commit/5138c1aa260ca530af231815381acd192b136c03

**Comment by brimworks** [comment]
Tested and implemented.
