### ISSUE TITLE
Separate recipe for creating distelli user/group

### ISSUE THREAD

**Issue by umcodemonkey** [Distelli/DistelliAgentCookbook#4]
Our setup process needs to create directories that are owned by the distelli user before installing the agent. It would be best if the cookbook had a recipe for that.

**Comment by brimworks** [comment]
This git repo currently contains a single recipe. I think I would need to move all the files so we can have multiple recipes defined, no?

FWIW, there is nothing special about the distelli user and your free to configure that user as you see fit, although it is useful to give that user `sudo` permissions so your deploy scripts can use `sudo`.

Here is a snippet that you should be able to use to create the distelli user:

```ruby
user "distelli" do
  supports :manage_home => true
  comment "Distelli User"
  home "/home/distelli"
  shell "/bin/bash"
end

# ...and give sudoers permissions:
file "/etc/sudoers.d/distelli" do
    content = "distelli ALL=(ALL) NOPASSWD:ALL\nDefaults:distelli !requiretty"
    mode="0400"
    owner="root"
end
```

(untested)

**Comment by umcodemonkey** [comment]
This repo contains a single cookbook, which currently has one recipe, `default`. The snippet you created could be put into a `create_user.rb` in the recipes directory, which would be sufficient. (I can envision other useful recipes, like `uninstall` or `upgrade agent` that would do different bits of work, but those are outside the scope of this issue.)

**Comment by brimworks** [comment]
Okay, I've checked in this recipe:

https://github.com/Distelli/DistelliAgentCookbook/commit/bc7da9f356575e57c4af57f8292eefb1d81b6549

...still untested. Let me know if this works for.

Thanks,
-Brian

**Comment by brimworks** [comment]
Tested and implemented.
